language: node_js
node_js:
- "8.6.0"

deploy:
  provider: heroku
  api_key:
    secure: "007bc40f-85fb-4c7f-91fe-f570bcb2ad0d"
  app:
    master: tp-devops-production
    develop: tp-devops-staging

script: echo "Running tests against $(node -v)..."

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
